# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-31 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bouncy', '0004_increase_processing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bounce',
            name='action',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='bounce',
            name='bounce_subtype',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Bounce Subtype'),
        ),
        migrations.AlterField(
            model_name='bounce',
            name='bounce_type',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Bounce Type'),
        ),
        migrations.AlterField(
            model_name='bounce',
            name='feedback_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time'),
        ),
        migrations.AlterField(
            model_name='bounce',
            name='hard',
            field=models.BooleanField(db_index=True, verbose_name='Hard Bounce'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='feedback_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='feedback_type',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Complaint Type'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='feedback_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time'),
        ),
    ]
