# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-09 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bouncy', '0005_auto_20190731_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_messageid', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
                ('clicked_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('useragent', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('link_tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_messageid', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
                ('delayed_time', models.DateTimeField(blank=True, null=True)),
                ('delay_type', models.TextField(blank=True, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('reporting_mta', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('diagnostic_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_messageid', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
                ('opened_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('useragent', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_messageid', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderingFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_messageid', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
                ('template_name', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sns_topic', models.CharField(max_length=350)),
                ('sns_messageid', models.CharField(max_length=100)),
                ('mail_timestamp', models.DateTimeField()),
                ('mail_id', models.CharField(max_length=100)),
                ('mail_from', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('feedback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Feedback Time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
